version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
    ports:
      - "12312:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nats:
    image: nats-streaming
    command: ["-p", "4222", "-m", "8222", "--store", "file", "--dir", "/data"]
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./data/nats:/data